Repository Joe91/fun-bots, pull requests merged in 2021-07, with the labels that each got.

#83 Rework for traces.md, making it easier and more clear to understand on how to create traces
  Screenshots/Menu/Traces/FullTraceMenuExample.png
  documentation/images/traces/DeployBaseAddObjExample.png
  documentation/images/traces/DeployBaseAddObjSuccess.png
  documentation/images/traces/PathMultipleFlags.png
  documentation/images/traces/TraceExampleA.png
  documentation/traces.md
  traces.md
Labels: documentation, enhancement

#84 Added issue templates for Github
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-enhancement.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/traces-bug-report.yml
  .gitignore
Labels: documentation

#86 Add the security policy
  .github/SECURITY.md
Labels: documentation

#87 Update project documentation
  .github/CODE_OF_CONDUCT.md
  .github/CODING_GUIDELINES.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/PULL_REQUEST_TEMPLATE/bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/documentation-update.md
  .github/PULL_REQUEST_TEMPLATE/new-traces.md
  .github/PULL_REQUEST_TEMPLATE/translation-update.md
Labels: documentation

#91 Update project documentation
  .github/CODE_OF_CONDUCT.md
  .github/CODING_GUIDELINES.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation-enhancement.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/traces-bug-report.yml
Labels: documentation

#124 Fixed a few errors.
  ext/Shared/WeaponList.lua
Labels: enhancement

#135 Updated Github issue forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: documentation

#137 Auto updater change to only support stable and dev builds
  ext/Server/UpdateCheck.lua
  ext/Server/__init__.lua
  ext/Shared/Config.lua
  ext/Shared/Version.lua
  mod.json
Labels: enhancement

#139 Make update check async
  ext/Server/UpdateCheck.lua
Labels: enhancement
